server:
  port: 8080
spring:
  application:
    name: "franchise-api"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27017/test"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

resilience4j:
  circuitbreaker:
    instances:
      franchiseCircuitBreaker:
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        registerHealthIndicator: true
